### ISSUE TITLE
Daylight Savings button does not toggle DST in clock

### ISSUE THREAD

**Issue by royvandongen** [jdwolin/enLIGHTen-LED-Clock#2]
When toggling the DST switch in the GUI, the clock does not ack this. It seems like the action to enable daylight savings time is not picked up in the clock, while it is beeing sent over an .ws connection.

**Comment by jdwolin** [comment]
I believe this is related to the failed dependencies:  Thank you for notifying of this bug. Go to the ipaddress of you clock 192.168.xx.xx/upload. This will bring you to the upload page for the webpage firmware. Please upload the new index.html file located here: https://github.com/jdwolin/enLIGHTen-LED-Clock/blob/master/Web%20Server/index.htm

Once that is updated, the rest of the dependencies should load. Let me know if that worked.

**Comment by royvandongen** [comment]
Toggling DST switch still has no effect on the clock itself, also, when reloading the GUI, the preset value is not recalled and shown in the config.

**Comment by royvandongen** [comment]
It seems like it has something to do with the code:
```
      if (strcmp((char *)payload, "daylighton") == 0 ) {
        dayflag = -2;
        webSocket.sendTXT(num, "OK");
      }

      if (strcmp((char *)payload, "daylightoff") == 0 ) {
        dayflag = -1;
        webSocket.sendTXT(num, "OK");
      }
```

in request_handlers.h. The value -2 is set there, and the webpage javascript looks for a '1'

**Comment by jdwolin** [comment]
You are correct in your analysis and thanks for helping me squash this bug.  Please upload index.html once more and it should work.  It works for me.  Go to the ipaddress of you clock 192.168.xx.xx/upload. This will bring you to the upload page for the webpage firmware. Please upload the new index.html file located here: https://github.com/jdwolin/enLIGHTen-LED-Clock/blob/master/Web%20Server/index.htm
