### ISSUE TITLE
Clock GUI/Interface does not show stored timezone

### ISSUE THREAD

**Issue by royvandongen** [jdwolin/enLIGHTen-LED-Clock#3]
When connecting to the webinterface of the clock, the current timezone is not shown. It seems the setting is not retrieved or parsed correctly in the webgui.

**Comment by jdwolin** [comment]
I believe this is related to the failed dependencies.  . Go to the ipaddress of you clock 192.168.xx.xx/upload. This will bring you to the upload page for the webpage firmware. Please upload the new index.html file located here: https://github.com/jdwolin/enLIGHTen-LED-Clock/blob/master/Web%20Server/index.htm

Once that is updated, the rest of the dependencies should load. Let me know if that worked.

**Comment by royvandongen** [comment]
Unfortunatly this did not solve the timezone issue.

**Comment by jdwolin** [comment]
This is a known issue and in order to correct it, the firmware would have to be further developed in the clocks and would have to be changed.  The clock is not in further development so this issue will be closed.
