### ISSUE TITLE
WebGUI has broken dependencies on external websites

### ISSUE THREAD

**Issue by royvandongen** [jdwolin/enLIGHTen-LED-Clock#4]
When checking the functionality of the app, multiple HTTP 404's where seen in the devbar.

There seem to be multiple dependencies for icon images loaded from the website brightlightart.com. This website does not exist (any more).

Also, jquery.js files are beeing pulled from the brightlightart.com website, which fail to resolve. resulting in unknown missing functionality of the clock webgui.

**Comment by jdwolin** [comment]
Thank you for notifying of this bug.  Go to the ipaddress of you clock 192.168.xx.xx/upload.  This will bring you to the upload page for the webpage firmware.  Please upload the new index.html file located here:  https://github.com/jdwolin/enLIGHTen-LED-Clock/blob/master/Web%20Server/index.htm

Once that is updated, the rest of the dependencies should load.  Let me know if that worked.

**Comment by royvandongen** [comment]
The broken dependencies seem to be met, there are no 404's anymore, icons are loaded and jquery library is available.

**Comment by jdwolin** [comment]
Glad it's working
